## DataSource (H2 in-memory by default)
spring.datasource.url=jdbc:h2:mem:phones;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true


# liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.batch.job.enabled=false
spring.batch.initialize-schema=always

## CSV import batch step
batch.chunk.size=1000

## Web server
server.port=8080

## Logging
logging.level.org.springframework.jdbc.core.JdbcTemplate=INFO
